"""Bot-maintained indexes.

Two files per target: `index.md` for a human or a coding agent arriving at the
problem, and `index.json` for tooling that would otherwise parse markdown. Both
list the Lean declarations each contribution provides, which is what someone
needs before deciding whether a target has already been covered.

Indexes are rebuilt on `main` after a merge, never inside a contribution PR. If
every contribution edited an index, every contribution PR would conflict with
every other one — and content-addressed directories exist precisely so they
never do.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .lean import LEAN_SUFFIX, declarations
from .model import METADATA_FILENAME, Contribution, SchemaError
from .pool import Pool, Target
from .store import iter_contributions

INDEX_MD = "index.md"
INDEX_JSON = "index.json"
SCHEMA_VERSION = 2
TASKS_REPOSITORY = "https://github.com/conjectures-io/conjectures-tasks"
GENERATED = (
    "<!-- Generated by `contrib-admin index`. Do not edit by hand; "
    "CI overwrites this file on main. -->"
)
DECLARATIONS_SHOWN = 4
ADDRESS_HEAD = 6
ADDRESS_TAIL = 6
COMMIT_CHARS = 40
ID_CHARS_SHOWN = 12
STATEMENT_WORDS = 60


# Index tables want the ends of an address, which are what a miner recognises.
def shorten(address: str) -> str:
    if len(address) <= ADDRESS_HEAD + ADDRESS_TAIL + 1:
        return address
    return f"{address[:ADDRESS_HEAD]}…{address[-ADDRESS_TAIL:]}"


@dataclass(frozen=True, slots=True)
class Entry:
    contribution: Contribution
    directory: Path
    added: str
    declarations: tuple[str, ...]

    @property
    def identifier(self) -> str:
        return str(self.contribution.contribution_id)

    @property
    def hotkey(self) -> str:
        reward = self.contribution.payload.reward
        return "" if reward is None else str(reward.hotkey)

    @property
    def coldkey(self) -> str:
        reward = self.contribution.payload.reward
        return "" if reward is None else str(reward.coldkey)

    def to_json(self) -> dict[str, Any]:
        payload = self.contribution.payload
        return {
            "added": self.added,
            "artifacts": [str(a.name) for a in payload.artifacts],
            "author": str(payload.author),
            "coldkey": self.coldkey or None,
            "contribution_id": self.identifier,
            "declarations": list(self.declarations),
            "hotkey": self.hotkey or None,
            "kind": str(payload.kind),
            "mode": str(payload.mode),
            "parents": [str(p) for p in payload.parents],
            "path": f"{self.identifier}/",
            "tasks_commit": payload.tasks_commit,
            "title": payload.title,
        }


@dataclass
class Section:
    slug: str
    target: Target | None = None
    statement: str = ""
    entries: list[Entry] = field(default_factory=list[Entry])


# The commit this checkout pins, not the Formal Conjectures commit the pool
# records: links must resolve in the repository that actually holds the bundles.
def pinned_tasks_commit(root: Path) -> str:
    attempts = (
        ["git", "rev-parse", "HEAD:conjectures"],
        ["git", "-C", "conjectures", "rev-parse", "HEAD"],
    )
    for argv in attempts:
        result = subprocess.run(  # noqa: S603 - argv is literal; git resolves on PATH
            argv, cwd=root, capture_output=True, text=True, check=False
        )
        commit = result.stdout.strip()
        if result.returncode == 0 and len(commit) == COMMIT_CHARS:
            return commit
    return "main"


def _added(root: Path, directory: Path) -> str:
    result = subprocess.run(  # noqa: S603
        [  # noqa: S607 - same literal-argv, git-on-PATH convention as cli/git.py
            "git",
            "log",
            "--diff-filter=A",
            "--format=%cd",
            "--date=format-local:%Y-%m-%d",
            "-1",
            "--",
            directory.relative_to(root).as_posix(),
        ],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
        env={"TZ": "UTC", "PATH": "/usr/bin:/bin"},
    )
    return result.stdout.strip()


def _statement(pool_root: Path, target: Target) -> str:
    for tier_directory in sorted(p for p in (pool_root / "pool").glob("*") if p.is_dir()):
        for bundle in target.bundles.values():
            metadata = tier_directory / bundle / "source-metadata.json"
            if not metadata.is_file():
                continue
            docstring = json.loads(metadata.read_text(encoding="utf-8")).get("docstring") or ""
            words = docstring.split()
            if not words:
                continue
            trimmed = " ".join(words[:STATEMENT_WORDS])
            return trimmed + ("…" if len(words) > STATEMENT_WORDS else "")
    return ""


def collect(root: Path, contributions_root: Path, pool_root: Path, pool: Pool) -> list[Section]:
    by_slug = {str(slug): target for slug, target in pool.targets.items()}
    sections: dict[str, Section] = {}
    for slug in sorted({*by_slug, *(p.name for p in contributions_root.glob("*") if p.is_dir())}):
        target = by_slug.get(slug)
        sections[slug] = Section(
            slug=slug,
            target=target,
            statement=_statement(pool_root, target) if target is not None else "",
        )

    for directory in iter_contributions(contributions_root):
        slug = directory.parent.name
        try:
            raw = json.loads((directory / METADATA_FILENAME).read_text(encoding="utf-8"))
            contribution = Contribution.parse(raw)
        except (OSError, json.JSONDecodeError, SchemaError):
            # An unreadable record is C001's finding; the index simply skips it.
            continue
        declared: list[str] = []
        for artifact in contribution.payload.artifacts:
            path = directory / str(artifact.name)
            if str(artifact.name).endswith(LEAN_SUFFIX) and path.is_file():
                declared.extend(declarations(path.read_text(encoding="utf-8")))
        sections.setdefault(slug, Section(slug=slug)).entries.append(
            Entry(contribution, directory, _added(root, directory), tuple(declared))
        )

    for section in sections.values():
        section.entries.sort(key=lambda e: (e.added, e.identifier))
    return [sections[slug] for slug in sorted(sections)]


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_target_md(section: Section, tasks_commit: str, tier: str) -> str:
    lines = [f"# {section.slug}", "", GENERATED, ""]
    target = section.target
    if target is None:
        lines += [
            "This target is no longer in the pinned pool. Its contributions are kept for the",
            "record; new ones are not accepted.",
            "",
        ]
    else:
        lines += [
            (f"**Problem** `{target.problem_id}` · **Reward target** `{target.reward_target_id}`"),
            "",
        ]
        bundles = " · ".join(
            f"[`{mode}`]({TASKS_REPOSITORY}/tree/{tasks_commit}/pool/{tier}/{name})"
            for mode, name in sorted(target.bundles.items())
        )
        lines += [f"Task bundles: {bundles}", ""]
    if section.statement:
        lines += [f"> {section.statement}", ""]

    lines += [f"## Contributions ({len(section.entries)})", ""]
    if not section.entries:
        lines += ["None yet. See [`guidelines.md`](../../guidelines.md) for how to add one.", ""]
        return "\n".join(lines)

    lines += [
        "| # | Added | Contribution | Title | Kind | Mode | Declarations | Hotkey |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for position, entry in enumerate(section.entries, start=1):
        payload = entry.contribution.payload
        shown = entry.declarations[:DECLARATIONS_SHOWN]
        rendered = ", ".join(f"`{name}`" for name in shown) or "—"
        remaining = len(entry.declarations) - len(shown)
        if remaining > 0:
            rendered += f" +{remaining}"
        lines.append(
            f"| {position} | {entry.added or '—'} "
            f"| [`{entry.identifier[:ID_CHARS_SHOWN]}`]({entry.identifier}/) "
            f"| {_escape(payload.title)} | {payload.kind} | {payload.mode} "
            f"| {rendered} | {f'`{shorten(entry.hotkey)}`' if entry.hotkey else '—'} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_target_json(section: Section) -> str:
    target = section.target
    payload = {
        "schema_version": SCHEMA_VERSION,
        "target": section.slug,
        "problem_id": target.problem_id if target else None,
        "reward_target_id": target.reward_target_id if target else None,
        "open": target is not None,
        "contribution_count": len(section.entries),
        "contributions": [entry.to_json() for entry in section.entries],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render_root_md(sections: list[Section], tasks_commit: str) -> str:
    populated = [s for s in sections if s.entries]
    total = sum(len(s.entries) for s in populated)
    lines = [
        "# Contribution index",
        "",
        GENERATED,
        "",
        f"{total} contribution(s) across {len(populated)} of {len(sections)} targets.",
        "",
        (
            "The targets themselves are listed in the pinned pool: "
            f"[`pool/`]({TASKS_REPOSITORY}/tree/{tasks_commit}/pool)."
        ),
        "",
    ]
    if not populated:
        lines += ["No contributions yet. See [`guidelines.md`](../guidelines.md).", ""]
        return "\n".join(lines)
    lines += ["| Target | Contributions | Latest |", "| --- | --- | --- |"]
    lines += [
        f"| [`{s.slug}`]({s.slug}/index.md) | {len(s.entries)} | {s.entries[-1].added or '—'} |"
        for s in populated
    ]
    lines.append("")
    return "\n".join(lines)


def build(
    root: Path,
    contributions_root: Path,
    pool_root: Path,
    pool: Pool,
    *,
    check: bool = False,
) -> tuple[str, ...]:
    """Write, or verify, every index. Returns the paths that differ."""
    sections = collect(root, contributions_root, pool_root, pool)
    tasks_commit = pinned_tasks_commit(root)

    targets: dict[Path, str] = {}
    for section in sections:
        directory = contributions_root / section.slug
        targets[directory / INDEX_MD] = render_target_md(section, tasks_commit, pool.tier)
        if section.entries:
            targets[directory / INDEX_JSON] = render_target_json(section)
    targets[contributions_root / INDEX_MD] = render_root_md(sections, tasks_commit)

    stale: list[str] = []
    for path, content in sorted(targets.items()):
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        stale.append(path.relative_to(root).as_posix())
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return tuple(stale)
