# The Rust extension ships no py.typed. Only the slice this project depends on is declared,
# so an upstream change to any of it fails type checking instead of silently degrading to Any.
# Verified against bittensor-core 0.1.3.

CRYPTO_ED25519: int
CRYPTO_SR25519: int

class Keypair:
    def __init__(
        self,
        ss58_address: str | None = ...,
        public_key: bytes | None = ...,
        crypto_type: int = ...,
        ss58_format: int = ...,
    ) -> None: ...
    @classmethod
    def create_from_uri(cls, uri: str) -> Keypair: ...
    @property
    def ss58_address(self) -> str: ...
    @property
    def public_key(self) -> bytes: ...
    @property
    def crypto_type(self) -> int: ...
    @property
    def ss58_format(self) -> int: ...
    def sign(self, message: bytes) -> bytes: ...
    def verify(self, message: bytes, signature: bytes) -> bool: ...

def ss58_decode(address: str) -> bytes: ...
def ss58_encode(public_key: bytes, ss58_format: int) -> str: ...
def deserialize_keypair_from_keyfile_data(data: bytes) -> Keypair: ...
def serialized_keypair_to_keyfile_data(keypair: Keypair) -> bytes: ...
def keyfile_data_is_encrypted(data: bytes) -> bool: ...
def encrypt_keyfile_data(data: bytes, password: str) -> bytes: ...
